# Generated by Django 4.0.3 on 2022-12-03 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(default=None, max_length=50, null=True)),
                ('LastName', models.CharField(default=None, max_length=50, null=True)),
                ('Password', models.CharField(default=None, max_length=20, null=True)),
                ('Occupation', models.CharField(default=None, max_length=40, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=None, max_length=6, null=True)),
                ('DateofBirth', models.DateField(default=None, null=True)),
                ('State', models.CharField(default=None, max_length=40, null=True)),
                ('Country', models.CharField(default=None, max_length=40, null=True)),
                ('Education', models.CharField(default=None, max_length=40, null=True)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fory', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
