# Generated by Django 4.0.3 on 2022-12-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='image',
        ),
        migrations.AddField(
            model_name='details',
            name='EmailName',
            field=models.EmailField(default='hai@123.com', max_length=254, null=True),
        ),
    ]
